"""CLI dispatcher: argparse parser construction and the main entrypoint.

Every cmd_* handler lives in harness.py (or its extracted siblings) and is
referenced through the `_h` alias. The dual-lookup below handles both
invocation paths transparently — when `python harness.py` runs as a script,
the module is loaded under `__main__`; when it is imported (tests, the
campaign adapter subprocess), it is loaded under `harness`. Either way `_h`
ends up bound to the live module so cmd_* references resolve.
"""
from __future__ import annotations

import argparse
import os
import sys

from core import HARNESS_VERSION, TRIAGE_VERDICTS


_h = sys.modules.get("harness") or sys.modules.get("__main__")
if _h is None or not hasattr(_h, "cmd_orient"):
    import harness as _h  # noqa: E402


def build_parser() -> argparse.ArgumentParser:
    parser = argparse.ArgumentParser(description="Evidence-gated vulnerability research harness for authorized assessment.")
    parser.add_argument("--version", action="version", version=HARNESS_VERSION)
    sub = parser.add_subparsers(required=True)

    p = sub.add_parser("commands", help="emit machine-readable command manifest")
    p.add_argument("--json", action="store_true", help="kept for compatibility; output is always JSON")
    p.set_defaults(func=_h.cmd_commands)

    p = sub.add_parser("explain", help="show command help plus relevant knowledge pointers")
    p.add_argument("command")
    p.set_defaults(func=_h.cmd_explain)

    p = sub.add_parser("knowledge", help="search local harness knowledge and corpus")
    p.add_argument("query")
    p.add_argument("--limit", type=int, default=8)
    p.add_argument("--snippets", type=int, default=3)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_knowledge)

    p = sub.add_parser("session-start", help="emit JSON cold-start context for a run")
    p.add_argument("run_dir")
    p.set_defaults(func=_h.cmd_session_start)

    p = sub.add_parser("next-action", help="recommend the next workflow action")
    p.add_argument("run_dir")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_next_action)

    p = sub.add_parser("orient", help="issue the next binding step (step contract)")
    p.add_argument("run_dir")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_orient)

    p = sub.add_parser("intent-set", help="record the run's threat model (orders hypotheses, weights scoring)")
    p.add_argument("run_dir")
    p.add_argument("--threat", action="append", required=True, choices=sorted(_h.INTENT_VOCAB), help="threat-model token (repeatable, priority order)")
    p.add_argument("--rationale", default="", help="why this threat model for this target")
    p.set_defaults(func=_h.cmd_intent_set)

    p = sub.add_parser("intent-show", help="show the run's recorded threat model")
    p.add_argument("run_dir")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_intent_show)

    p = sub.add_parser("submit", help="record the pending step outcome and advance the loop cursor")
    p.add_argument("run_dir")
    p.add_argument("--triage-verdict", choices=sorted(TRIAGE_VERDICTS), help="verdict to record when the pending step is a triage gate")
    p.add_argument("--note", default="", help="free-text note attached to the step outcome")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_submit)

    p = sub.add_parser("loop-integrity-check", help="validate the loop cursor (run or bundled fixtures)")
    p.add_argument("--run-dir", default="", help="validate a specific run; omit to run bundled fixtures")
    p.add_argument("--fail", action="store_true", help="exit non-zero if any check fails")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_loop_integrity_check)

    p = sub.add_parser("intent-ordering-check", help="validate intent reorders hypotheses (bundled fixture)")
    p.add_argument("--fail", action="store_true", help="exit non-zero if any check fails")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_intent_ordering_check)

    p = sub.add_parser("budget", help="compare run elapsed time with target budgets")
    p.add_argument("run_dir")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_budget)

    p = sub.add_parser("corpus-rebuild", help="rebuild append-only candidate corpus from runs")
    p.set_defaults(func=_h.cmd_corpus_rebuild)

    p = sub.add_parser("retro", help="write run retrospective and reviewable knowledge patch")
    p.add_argument("run_dir")
    p.set_defaults(func=_h.cmd_retro)

    p = sub.add_parser("pick-target", help="rank target profiles by expected value signals")
    p.add_argument("--budget-minutes", type=int)
    p.add_argument("--platform")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_pick_target)

    p = sub.add_parser("campaign-plan", help="rank reusable campaign modules for a target")
    p.add_argument("target", help="target id or target profile path")
    p.add_argument("--limit", type=int, default=5)
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_plan)

    p = sub.add_parser("campaign-adapter-check", help="validate campaign adapter manifests")
    p.add_argument("--target", help="target id or target profile path")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true", help="exit non-zero if any adapter fails validation")
    p.set_defaults(func=_h.cmd_campaign_adapter_check)

    p = sub.add_parser("mutation-plan", help="generate module mutation coverage from target adapter metadata")
    p.add_argument("target", help="target id or target profile path")
    p.add_argument("--module", help="generic module id or adapter-local module name")
    p.add_argument("--run-dir", help="write JSON under run evidence/mutation_coverage")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_mutation_plan)

    p = sub.add_parser("mutation-coverage-check", help="validate runtime mutation_coverage artifacts")
    p.add_argument("path", help="campaign/test/run directory or JSON artifact")
    p.add_argument("--allow-missing", action="store_true", help="warn instead of fail for legacy artifacts without mutation_coverage")
    p.add_argument("--allow-unknown-variants", action="store_true", help="warn instead of fail when coverage names variants outside the catalog")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true", help="exit non-zero if validation fails")
    p.set_defaults(func=_h.cmd_mutation_coverage_check)

    p = sub.add_parser("patch-first-plan", help="rank patch/advisory novelty seeds before broad scanning")
    p.add_argument("target", help="target id or target profile path")
    p.add_argument("--limit", type=int, default=12)
    p.add_argument("--timeout", type=int, default=10)
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_patch_first_plan)

    p = sub.add_parser("campaign-dashboard", help="summarize target campaign coverage and required next actions")
    p.add_argument("target", help="target id or target profile path")
    p.add_argument("--limit", type=int, default=8)
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_dashboard)

    p = sub.add_parser("campaign-run", help="execute adapter modules through the generic campaign runner")
    p.add_argument("--target", help="target id or target profile path")
    p.add_argument("--adapter", help="adapter manifest path")
    p.add_argument("--module", action="append", help="generic module id or local module name; repeatable")
    p.add_argument("--out-dir")
    p.add_argument("--timeout", type=int, default=120)
    p.add_argument("--allowed-exit-code", action="append", type=int, help="allowed module exit code; default 0")
    p.add_argument("--dry-run", action="store_true")
    p.add_argument("--validate-mutation", action="store_true")
    p.add_argument("--allow-missing-mutation", action="store_true")
    p.add_argument("--allow-unknown-variants", action="store_true")
    p.add_argument("--skip-adapter-check", action="store_true")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_run)

    p = sub.add_parser("campaign-gate", help="enforce lifecycle checks on a campaign-run directory")
    p.add_argument("campaign_dir")
    p.add_argument("--revalidate-mutation", action="store_true")
    p.add_argument("--allow-missing-mutation", action="store_true")
    p.add_argument("--allow-unknown-variants", action="store_true")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_gate)

    p = sub.add_parser("campaign-start", help="start a structured campaign workspace for a target")
    p.add_argument("target", help="target id or target profile path")
    p.add_argument("--name", help="campaign folder name; defaults to timestamp")
    p.add_argument("--out-dir", help="override campaign directory")
    p.add_argument("--refresh-advisories", action="store_true", help="poll OSV/GHSA-style advisories into the watch queue before planning")
    p.add_argument("--refresh-source", choices=["osv", "ghsa", "both"], default="both")
    p.add_argument("--refresh-ecosystem", help="override advisory ecosystem, e.g. PyPI, Go, npm")
    p.add_argument("--refresh-package", help="override advisory package/module name")
    p.add_argument("--refresh-package-alias", action="append", help="additional advisory package alias for matching")
    p.add_argument("--refresh-fixture", help="local OSV/GHSA-style advisory fixture for offline refresh testing")
    p.add_argument("--refresh-timeout", type=int, default=20)
    p.add_argument("--refresh-seed", action=argparse.BooleanOptionalAction, default=True, help="queue current advisory state during campaign start")
    p.add_argument("--refresh-ephemeral-state", action="store_true", help="do not persist watch state for this refresh")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_start)

    p = sub.add_parser("campaign-flow-check", help="run bundled campaign/advisory/queue/candidate acceptance flow")
    p.add_argument("--out-dir")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true")
    p.set_defaults(func=_h.cmd_campaign_flow_check)

    p = sub.add_parser("score-tune", help="produce score-weight tuning report from terminal submissions")
    p.add_argument("--since")
    p.add_argument("--min-terminal", type=int, default=20)
    p.set_defaults(func=_h.cmd_score_tune)

    p = sub.add_parser("outcome-record", help="record a terminal BB/VAPT outcome with candidate metadata")
    p.add_argument("--submission-id")
    p.add_argument("--run-dir")
    p.add_argument("--candidate-id")
    p.add_argument("--status", required=True)
    p.add_argument("--platform")
    p.add_argument("--program")
    p.add_argument("--title")
    p.add_argument("--submitted-at")
    p.add_argument("--severity-claimed")
    p.add_argument("--severity")
    p.add_argument("--cvss")
    p.add_argument("--payout", type=float)
    p.add_argument("--currency")
    p.add_argument("--lesson")
    p.add_argument("--note")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_outcome_record)

    p = sub.add_parser("outcome-tune", help="build outcome-derived tuning weights for scoring and campaign planning")
    p.add_argument("--since")
    p.add_argument("--out")
    p.add_argument("--json", action="store_true")
    p.add_argument("--include-synthetic", action="store_true", help="include rows tagged synthetic:true (off by default)")
    p.set_defaults(func=_h.cmd_outcome_tune)

    p = sub.add_parser("outcome-tune-check", help="run fixture acceptance check for outcome-driven tuning")
    p.add_argument("--out-dir")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true")
    p.set_defaults(func=_h.cmd_outcome_tune_check)

    p = sub.add_parser("weights", help="inspect effective outcome-tuning weights")
    weights_sub = p.add_subparsers(required=True)
    sp = weights_sub.add_parser("show", help="show current effective weights and last meaningful update")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_weights_show)

    p = sub.add_parser("phase2-check", help="run Phase 2 feedback-loop acceptance checks")
    p.add_argument("--run-dir", default="vapt/harness/tests/results/phase2_check_run")
    p.add_argument("--target-id", default="demo")
    p.add_argument("--refresh-retro", action="store_true")
    p.set_defaults(func=_h.cmd_phase2_check)

    p = sub.add_parser("phase3-check", help="run Phase 3 tooling/probe acceptance checks")
    p.add_argument("--run-dir", default="vapt/harness/tests/results/phase3_check_run")
    p.set_defaults(func=_h.cmd_phase3_check)

    p = sub.add_parser("phase4-check", help="run Phase 4 watch/queue acceptance checks")
    p.set_defaults(func=_h.cmd_phase4_check)

    p = sub.add_parser("phase4-remote-check", help="validate Phase 4 live remote polling")
    p.add_argument("--timeout", type=int, default=20)
    p.set_defaults(func=_h.cmd_phase4_remote_check)

    p = sub.add_parser("phase4-soak-check", help="run a bounded Phase 4 daemon soak check")
    p.add_argument("--target")
    p.add_argument("--seconds", type=int, default=10)
    p.add_argument("--iterations", type=int, default=3)
    p.add_argument("--interval-seconds", type=int, default=1)
    p.add_argument("--timeout", type=int, default=20)
    p.add_argument("--require-24h", action="store_true")
    p.set_defaults(func=_h.cmd_phase4_soak_check)

    p = sub.add_parser("watch-add", help="add a Phase 4 watch source to a target profile")
    p.add_argument("target_id")
    p.add_argument("--source", required=True, choices=["github_commits", "github_releases", "ghsa_advisories", "osv_advisories"])
    p.add_argument("--repo", help="owner/repo for remote GitHub polling")
    p.add_argument("--repo-path", help="local git checkout path for offline commit/release polling")
    p.add_argument("--branch", default="HEAD")
    p.add_argument("--path", action="append", help="source path filter for commit watches")
    p.add_argument("--ecosystem", help="package ecosystem for advisory watches")
    p.add_argument("--package", help="package name for advisory watches")
    p.add_argument("--package-alias", action="append", help="alternate package/module name for advisory matching")
    p.add_argument("--cwe", action="append", help="CWE id that should cross-reference advisories")
    p.add_argument("--fixture", help="local advisory fixture file for offline polling")
    p.add_argument("--trigger-pattern", action="append", help="surface category or literal pattern to queue on")
    p.add_argument("--poll-interval-minutes", type=int, default=30)
    p.add_argument("--allow-network", action="store_true", help="permit this source to use remote network polling")
    p.set_defaults(func=_h.cmd_watch_add)

    p = sub.add_parser("watch-list", help="list Phase 4 watch profiles")
    p.add_argument("--target")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_watch_list)

    p = sub.add_parser("watch-tick", help="run one Phase 4 watch polling pass")
    p.add_argument("--target")
    p.add_argument("--seed", action="store_true", help="queue current state even without prior state")
    p.add_argument("--timeout", type=int, default=30)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_watch_tick)

    p = sub.add_parser("watch-daemon", help="run repeated watch ticks with heartbeat logging")
    p.add_argument("--target")
    p.add_argument("--interval-seconds", type=int, default=1800)
    p.add_argument("--timeout", type=int, default=30)
    p.add_argument("--max-iterations", type=int, default=0)
    p.add_argument("--max-seconds", type=int, default=0)
    p.set_defaults(func=_h.cmd_watch_daemon)

    p = sub.add_parser("queue", help="list or claim Phase 4 queue entries")
    p.add_argument("--target")
    p.add_argument("--all", action="store_true", help="include claimed entries")
    p.add_argument("--json", action="store_true")
    queue_sub = p.add_subparsers(dest="queue_action")
    qp = queue_sub.add_parser("claim", help="claim a queue entry")
    qp.add_argument("queue_id")
    qp.add_argument("--claimed-by", default=os.environ.get("USER", "operator"))
    qp.add_argument("--run-dir")
    qp.add_argument("--force", action="store_true")
    qp.set_defaults(func=_h.cmd_queue_claim)
    p.set_defaults(func=_h.cmd_queue)

    p = sub.add_parser("probes", help="list reusable probe modules")
    p.set_defaults(func=_h.cmd_probes)

    p = sub.add_parser("probes-test", help="run reusable probes against captive fixture candidates")
    p.add_argument("--fixture", default="vapt/harness/tests/fixtures/probe_candidates.yaml")
    p.add_argument("--run-dir")
    p.add_argument("--probe")
    p.set_defaults(func=_h.cmd_probes_test)

    p = sub.add_parser("refine", help="run one or more probe-guided refinement iterations")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--probe")
    p.add_argument("--max-iterations", type=int, default=1)
    p.add_argument("--budget-minutes", type=int, default=30)
    p.set_defaults(func=_h.cmd_refine)

    p = sub.add_parser("playbook", help="generate a target-class BB/VAPT playbook for a run")
    p.add_argument("run_dir")
    p.add_argument("--kind", default="auto", choices=["auto", *sorted(_h.TARGET_PLAYBOOKS.keys())])
    p.set_defaults(func=_h.cmd_playbook)

    p = sub.add_parser("codeql-workflow", help="generate repeatable CodeQL workflow commands for a run")
    p.add_argument("run_dir")
    p.add_argument("--language", choices=sorted(_h.CODEQL_WORKFLOWS.keys()))
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_codeql_workflow)

    p = sub.add_parser("scaffold-poc", help="create a PoC scaffold for a vulnerability class and target")
    p.add_argument("vuln_class")
    p.add_argument("target_id")
    p.set_defaults(func=_h.cmd_scaffold_poc)

    p = sub.add_parser("new-probe", help="create a reusable probe skeleton")
    p.add_argument("name")
    p.add_argument("--vuln-class", required=True)
    p.add_argument("--description")
    p.add_argument("--force", action="store_true")
    p.set_defaults(func=_h.cmd_new_probe)

    p = sub.add_parser("sandbox-exec", help="run a command inside Docker/Podman or macOS sandbox-exec with no network egress")
    p.add_argument("run_dir")
    p.add_argument("--cmd", required=True)
    p.add_argument("--image", default="python:3.12-alpine")
    p.add_argument("--policy", default="none")
    p.add_argument("--mount", action="append", help="host path plus optional :ro/:rw")
    p.add_argument("--timeout", type=int, default=120)
    p.add_argument("--cpus", default="1")
    p.add_argument("--memory", default="512m")
    p.add_argument("--pids", type=int, default=128)
    p.set_defaults(func=_h.cmd_sandbox_exec)

    p = sub.add_parser("tool-gap-add", help="append an explicit tool/probe gap")
    p.add_argument("run_dir")
    p.add_argument("--candidate-id")
    p.add_argument("--missing-class", required=True)
    p.add_argument("--context")
    p.set_defaults(func=_h.cmd_tool_gap_add)

    p = sub.add_parser("tool-gaps", help="list ranked tool/probe gaps")
    p.add_argument("--json", action="store_true")
    p.add_argument("--entries", action="store_true")
    p.set_defaults(func=_h.cmd_tool_gaps)

    p = sub.add_parser("scan-semgrep", help="run semgrep with safe captured output")
    p.add_argument("run_dir")
    p.add_argument("--ruleset")
    p.add_argument("--timeout", type=int, default=120)
    p.set_defaults(func=_h.cmd_scan_semgrep)

    p = sub.add_parser("scan-bandit", help="run bandit with safe captured output")
    p.add_argument("run_dir")
    p.add_argument("--config")
    p.add_argument("--severity-level", default="low", choices=["low", "medium", "high"])
    p.add_argument("--confidence-level", default="low", choices=["low", "medium", "high"])
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_bandit)

    p = sub.add_parser("scan-pip-audit", help="run pip-audit against target Python dependency files")
    p.add_argument("run_dir")
    p.add_argument("--requirement")
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_pip_audit)

    p = sub.add_parser("scan-osv", help="run osv-scanner against target source/lockfiles")
    p.add_argument("run_dir")
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_osv)

    p = sub.add_parser("scan-codeql", help="run CodeQL database analysis with captured evidence")
    p.add_argument("run_dir")
    p.add_argument("--database")
    p.add_argument("--create-database", action="store_true")
    p.add_argument("--language", choices=["go", "python", "javascript-typescript", "cpp", "csharp", "java-kotlin", "ruby", "swift"])
    p.add_argument("--query")
    p.add_argument("--ql-pack")
    p.add_argument("--threads", type=int, default=2)
    p.add_argument("--timeout", type=int, default=900)
    p.set_defaults(func=_h.cmd_scan_codeql)

    p = sub.add_parser("scan-trufflehog", help="run trufflehog filesystem secret scan")
    p.add_argument("run_dir")
    p.add_argument("--only-verified", action="store_true")
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_trufflehog)

    p = sub.add_parser("scan-tls", help="run bounded TLS scan with sslyze or testssl.sh")
    p.add_argument("host")
    p.add_argument("--run-dir")
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_tls)

    p = sub.add_parser("scan-nuclei", help="run bounded nuclei template scan")
    p.add_argument("run_dir")
    p.add_argument("--url", required=True)
    p.add_argument("--template", action="append")
    p.add_argument("--allow-default-templates", action="store_true")
    p.add_argument("--rate-limit", type=int, default=2)
    p.add_argument("--concurrency", type=int, default=1)
    p.add_argument("--template-timeout", type=int, default=6)
    p.add_argument("--timeout", type=int, default=180)
    p.set_defaults(func=_h.cmd_scan_nuclei)

    p = sub.add_parser("scan-headers", help="capture HTTP headers for one URL")
    p.add_argument("url")
    p.add_argument("--timeout", type=int, default=15)
    p.set_defaults(func=_h.cmd_scan_headers)

    p = sub.add_parser("tool-health", help="list scanner/tool availability without running scans")
    p.add_argument("--json", action="store_true")
    p.add_argument("--versions", action="store_true")
    p.set_defaults(func=_h.cmd_tool_health)

    p = sub.add_parser("scan-zap-baseline", help="OWASP ZAP passive baseline scan (Move 3)")
    p.add_argument("run_dir")
    p.add_argument("target_url")
    p.add_argument("--timeout", type=int, default=600)
    p.add_argument("--network", default="bridge", help="container network mode; restrict per-target in production")
    p.add_argument("--extra", nargs="*", help="extra args passed to zap-baseline.py")
    p.set_defaults(func=_h.cmd_scan_zap_baseline)

    p = sub.add_parser("scan-zap-full", help="OWASP ZAP active full scan (Move 3, invasive)")
    p.add_argument("run_dir")
    p.add_argument("target_url")
    p.add_argument("--timeout", type=int, default=1800)
    p.add_argument("--network", default="bridge")
    p.add_argument("--extra", nargs="*")
    p.set_defaults(func=_h.cmd_scan_zap_full)

    p = sub.add_parser("scan-sqlmap", help="sqlmap injection detection in batch mode (Move 3)")
    p.add_argument("run_dir")
    p.add_argument("--target-url")
    p.add_argument("--request-file", help="path to raw HTTP request file")
    p.add_argument("--timeout", type=int, default=900)
    p.add_argument("--network", default="bridge")
    p.add_argument("--extra", nargs="*")
    p.add_argument(
        "--prefer-local",
        action="store_true",
        help="force the local sqlmap binary even when a container runtime is available",
    )
    p.set_defaults(func=_h.cmd_scan_sqlmap)

    p = sub.add_parser("scan-jwt", help="JWT decode + structural risk inspection (Move 3)")
    p.add_argument("run_dir")
    p.add_argument("--token", help="JWT to inspect")
    p.add_argument("--token-file", help="file containing JWT")
    p.add_argument("--container", action="store_true", help="also run jwt_tool container alongside local decode")
    p.add_argument("--timeout", type=int, default=120)
    p.set_defaults(func=_h.cmd_scan_jwt)

    p = sub.add_parser("scan-screenshot", help="Playwright screenshot of a target URL (Move 3)")
    p.add_argument("run_dir")
    p.add_argument("target_url")
    p.add_argument("--wait-ms", type=int, default=2000)
    p.add_argument("--network", default="bridge")
    p.add_argument("--timeout", type=int, default=120)
    p.add_argument(
        "--prefer-local",
        action="store_true",
        help="use the local playwright install even when a container runtime is available",
    )
    p.set_defaults(func=_h.cmd_scan_screenshot)

    p = sub.add_parser("scope-check", help="dry-run the fail-closed scope/ROE gate for a target_url without scanning")
    p.add_argument("run_dir")
    p.add_argument("target_url")
    p.add_argument("--scanner", default="zap-full", help="scanner name to evaluate (active scanners require active_scan_allowed)")
    p.set_defaults(func=_h.cmd_scope_check)

    p = sub.add_parser("tools-capability", help="report Move 3 toolchain availability (container or local)")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_tools_capability)

    p = sub.add_parser("source-acquire", help="Move 5: clone (or passthrough) a target source tree at a locked commit")
    p.add_argument("repo_url", help="git URL or absolute local path")
    p.add_argument("--commit", help="optional locked commit SHA")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_source_acquire)

    p = sub.add_parser("source-index", help="Move 5: walk a repo and list files by language")
    p.add_argument("repo_path", help="absolute path to an acquired source tree")
    p.add_argument("--max-files", type=int)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_source_index)

    p = sub.add_parser("source-probe", help="Move 5: run patch_variant_hunter source-reading probe against a local repo")
    p.add_argument("--local-path", help="absolute path to an acquired source tree")
    p.add_argument("--repo-url", help="git URL (will be acquired if not cached)")
    p.add_argument("--commit", help="commit SHA")
    p.add_argument("--run-dir", help="harness run dir for evidence (optional)")
    p.add_argument("--bug-classes", nargs="*", help="restrict to specific bug classes")
    p.add_argument("--max-files", type=int)
    p.add_argument("--head", type=int, default=20)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_source_probe)

    p = sub.add_parser("discovery-sweep", help="Move 4: sweep recent GHSA advisories for unwatched packages and queue proposals")
    p.add_argument("--severity-floor", default="high", choices=["low", "medium", "moderate", "high", "critical"])
    p.add_argument("--since-days", type=int, default=7)
    p.add_argument("--per-page", type=int, default=30)
    p.add_argument("--max-pages", type=int, default=4)
    p.add_argument("--timeout", type=int, default=20)
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_discovery_sweep)

    p = sub.add_parser("discovery-list", help="list auto-discovery proposals awaiting operator review")
    p.add_argument("--all", action="store_true", help="include claimed proposals")
    p.add_argument("--severity", action="append")
    p.add_argument("--ecosystem")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_discovery_list)

    p = sub.add_parser("discovery-claim", help="claim or reject an auto-discovery proposal")
    p.add_argument("slug", help="proposal filename, e.g. prop_GHSA-xxxx_pypi_foo.json")
    p.add_argument("--decision", default="claim", choices=["claim", "reject"])
    p.add_argument("--claimed-by", default=os.environ.get("USER", "operator"))
    p.add_argument("--note")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_discovery_claim)

    p = sub.add_parser("ingest-tool-scan", help="normalize scanner JSON/JSONL and optionally create auto-candidates")
    p.add_argument("run_dir")
    p.add_argument("artifact")
    p.add_argument(
        "--tool",
        required=True,
        choices=["bandit", "semgrep", "nuclei", "nuclei-jsonl", "pip-audit", "osv", "trufflehog"],
    )
    p.add_argument("--create-candidates", action="store_true")
    p.add_argument("--include-low", action="store_true")
    p.add_argument("--max-findings", type=int, default=50)
    p.set_defaults(func=_h.cmd_ingest_tool_scan)

    p = sub.add_parser("submissions", help="manage submission outcome ledger")
    sub_sub = p.add_subparsers(required=True)
    sp = sub_sub.add_parser("add", help="add a submitted candidate")
    sp.add_argument("run_dir")
    sp.add_argument("candidate_id")
    sp.add_argument("--platform", required=True)
    sp.add_argument("--id", required=True)
    sp.add_argument("--program")
    sp.add_argument("--title")
    sp.add_argument("--severity")
    sp.add_argument("--cvss")
    sp.add_argument("--note")
    sp.add_argument("--force", action="store_true")
    sp.set_defaults(func=_h.cmd_submission_add)

    sp = sub_sub.add_parser("update", help="append a submission status update")
    sp.add_argument("submission_id")
    sp.add_argument("--status", required=True)
    sp.add_argument("--payout", type=float)
    sp.add_argument("--currency")
    sp.add_argument("--note")
    sp.add_argument("--lesson")
    sp.set_defaults(func=_h.cmd_submission_update)

    sp = sub_sub.add_parser("list", help="list submissions")
    sp.add_argument("--program")
    sp.add_argument("--since")
    sp.add_argument("--final-only", action="store_true")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_submissions_list)

    sp = sub_sub.add_parser("stats", help="summarize submission outcomes")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_submissions_stats)

    sp = sub_sub.add_parser(
        "seed-synthetic",
        help="seed synthetic submission rows derived from the candidate corpus; rows are tagged synthetic:true and excluded from outcome-tune by default",
    )
    sp.add_argument("--clear", action="store_true", help="remove all synthetic rows instead of seeding")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_submission_seed_synthetic)

    p = sub.add_parser("osv-cache", help="manage the local OSV query cache used by dedup")
    osv_sub = p.add_subparsers(required=True)
    sp = osv_sub.add_parser("stats", help="show cache size and freshness")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_osv_cache_stats)
    sp = osv_sub.add_parser("prefetch", help="warm the cache for one or more targets")
    sp.add_argument("target", nargs="+", help="target id(s) under vapt/engagements/")
    sp.add_argument("--timeout", type=int, default=20)
    sp.add_argument("--refresh", action="store_true", help="bypass cache during prefetch (force fresh fetch)")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_osv_cache_prefetch)
    sp = osv_sub.add_parser("clear", help="delete the cache database")
    sp.add_argument("--json", action="store_true")
    sp.set_defaults(func=_h.cmd_osv_cache_clear)

    p = sub.add_parser("corpus", help="query cross-engagement corpus")
    corpus_sub = p.add_subparsers(required=True)
    cp = corpus_sub.add_parser("suggest", help="suggest reusable patterns for a target")
    cp.add_argument("target_id")
    cp.add_argument("--limit", type=int, default=10)
    cp.add_argument("--json", action="store_true")
    cp.set_defaults(func=_h.cmd_corpus_suggest)

    p = sub.add_parser("init", help="create a run from a target profile")
    p.add_argument("target")
    p.add_argument("--run-id")
    p.set_defaults(func=_h.cmd_init)

    p = sub.add_parser("prepare", help="fingerprint source and create prepare artifacts")
    p.add_argument("run_dir")
    p.add_argument("--allow-non-git", action="store_true", help="allow tarball/wheel sources without git metadata")
    p.set_defaults(func=_h.cmd_prepare)

    p = sub.add_parser("map", help="run lightweight source pattern mapping")
    p.add_argument("run_dir")
    p.add_argument("--max-hits", type=int, default=40)
    p.set_defaults(func=_h.cmd_map)

    p = sub.add_parser("surfaces-test", help="run regression tests for shared surface patterns")
    p.add_argument(
        "--corpus",
        default="vapt/harness/tests/surface_corpus",
        help="path to local regression corpus",
    )
    p.add_argument(
        "--expectations",
        default="vapt/harness/tests/surface_expectations.yaml",
        help="expected category hit counts",
    )
    p.add_argument("--timeout", type=int, default=30)
    p.add_argument("--max-hits", type=int, default=20)
    p.set_defaults(func=_h.cmd_surfaces_test)

    p = sub.add_parser("candidate-add", help="add a candidate to the ledger")
    p.add_argument("run_dir")
    p.add_argument("--title", required=True)
    p.add_argument("--surface", required=True)
    p.add_argument("--weakness", required=True)
    p.add_argument("--impact", required=True)
    p.add_argument("--attacker-control", required=True)
    p.add_argument("--sink", required=True)
    p.add_argument("--entrypoint")
    p.add_argument("--trust-boundary")
    p.add_argument("--latest-affected")
    p.add_argument("--cve")
    p.add_argument("--cwe")
    p.add_argument("--cvss")
    p.add_argument("--mitre-attack")
    p.add_argument("--mitre-atlas")
    p.add_argument("--d3fend")
    p.add_argument("--nist-csf")
    p.add_argument("--nist-ai-rmf")
    p.add_argument("--negative-controls")
    p.add_argument("--safety-notes")
    p.add_argument("--reference-sources")
    p.add_argument("--root-cause")
    p.add_argument("--variant-analysis")
    p.add_argument("--patch-diff")
    p.add_argument("--campaign-dir", help="explicit campaign-start workspace to attach to this candidate")
    p.add_argument("--campaign-module", help="generic module id or adapter-local module name that produced the candidate")
    p.add_argument("--campaign-run", help="campaign_run.json artifact to attach when already available")
    p.add_argument("--campaign-gate", help="campaign_gate.json artifact to attach when already available")
    p.add_argument("--no-campaign-context", action="store_true", help="do not auto-attach campaign_start context from parent directories")
    p.add_argument("--exploitability")
    p.add_argument("--disclosure-quality")
    p.add_argument("--notes")
    p.set_defaults(func=_h.cmd_candidate_add)

    p = sub.add_parser("candidate-from-queue", help="convert a claimed watch/advisory queue seed into a candidate")
    p.add_argument("run_dir")
    p.add_argument("queue_id")
    p.add_argument("--seed-index", type=int, default=0)
    p.add_argument("--claim", action="store_true", help="claim a pending queue entry before conversion")
    p.add_argument("--claimed-by", default=os.environ.get("USER", "operator"))
    p.add_argument("--force", action="store_true")
    p.add_argument("--title")
    p.add_argument("--surface")
    p.add_argument("--weakness")
    p.add_argument("--impact")
    p.add_argument("--attacker-control")
    p.add_argument("--sink")
    p.add_argument("--entrypoint")
    p.add_argument("--trust-boundary")
    p.add_argument("--latest-affected")
    p.add_argument("--novelty")
    p.add_argument("--cve")
    p.add_argument("--cwe")
    p.add_argument("--cvss")
    p.add_argument("--mitre-attack")
    p.add_argument("--mitre-atlas")
    p.add_argument("--d3fend")
    p.add_argument("--nist-csf")
    p.add_argument("--nist-ai-rmf")
    p.add_argument("--negative-controls")
    p.add_argument("--safety-notes")
    p.add_argument("--reference-sources")
    p.add_argument("--root-cause")
    p.add_argument("--variant-analysis")
    p.add_argument("--patch-diff")
    p.add_argument("--campaign-dir", help="explicit campaign-start workspace to attach to this candidate")
    p.add_argument("--campaign-module", help="generic module id or adapter-local module name that produced the candidate")
    p.add_argument("--campaign-run", help="campaign_run.json artifact to attach when already available")
    p.add_argument("--campaign-gate", help="campaign_gate.json artifact to attach when already available")
    p.add_argument("--no-campaign-context", action="store_true", help="do not auto-attach campaign_start context from parent directories")
    p.add_argument("--exploitability")
    p.add_argument("--disclosure-quality")
    p.add_argument("--notes")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_candidate_from_queue)

    p = sub.add_parser("candidate-link-campaign", help="link a candidate to a passed campaign-gate artifact")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--campaign-dir", required=True)
    p.add_argument("--module", required=True, help="generic module id or adapter-local module name")
    p.add_argument("--campaign-run")
    p.add_argument("--campaign-gate")
    p.add_argument("--no-require-gate", dest="require_gate", action="store_false")
    p.add_argument("--no-require-module-pass", dest="require_module_pass", action="store_false")
    p.add_argument("--json", action="store_true")
    p.add_argument("--fail", action="store_true")
    p.set_defaults(func=_h.cmd_candidate_link_campaign, require_gate=True, require_module_pass=True)

    p = sub.add_parser("dedup", help="run local duplicate/novelty gate")
    p.add_argument("run_dir")
    p.add_argument("candidate_id", nargs="?")
    p.add_argument(
        "--status",
        choices=[
            "unchecked",
            "known-duplicate",
            "possible-regression",
            "dedup-incomplete",
            "no-known-duplicate",
            "low-public-footprint",
        ],
    )
    p.add_argument("--regression", action="store_true")
    p.add_argument("--check-osv", action="store_true", help="query osv.dev and persist dedup evidence")
    p.add_argument("--osv-ecosystem", help="override target.osv_ecosystem, e.g. PyPI, Go, npm")
    p.add_argument("--osv-package", help="override target.osv_package")
    p.add_argument("--osv-version", help="override target version for OSV package query")
    p.add_argument("--osv-timeout", type=int, default=20)
    p.add_argument("--osv-cache-only", action="store_true", help="never touch the network; rely entirely on osv.sqlite cache")
    p.add_argument("--osv-fresh-only", action="store_true", help="bypass cache; always go to network")
    p.add_argument("--reference", action="append", help="manual duplicate/advisory source checked, e.g. huntr, github-advisories, github-issues")
    p.add_argument("--notes")
    p.set_defaults(func=_h.cmd_dedup)

    p = sub.add_parser("gate", help="check exploit-thesis promotion gate")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--promote", action="store_true")
    p.add_argument("--report-ready", action="store_true")
    p.set_defaults(func=_h.cmd_gate)

    p = sub.add_parser("report-gate", help="strict report-readiness gate for BB submissions")
    p.add_argument("run_dir")
    p.add_argument("candidate_id", nargs="?")
    p.add_argument("--mark-ready", action="store_true")
    p.add_argument("--fail", action="store_true", help="exit non-zero when any checked candidate is blocked")
    p.set_defaults(func=_h.cmd_report_gate)

    p = sub.add_parser("candidate-set", help="update candidate status")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--status", default=None)
    p.add_argument("--triage-verdict", choices=sorted(TRIAGE_VERDICTS), help="classify the flow during triage before any proof work")
    p.add_argument("--reason")
    p.add_argument("--force", action="store_true", help="override canonical workflow preconditions with history reason")
    p.add_argument("--entrypoint")
    p.add_argument("--trust-boundary")
    p.add_argument("--latest-affected")
    p.add_argument("--novelty")
    p.add_argument("--impact")
    p.add_argument("--attacker-control")
    p.add_argument("--sink")
    p.add_argument("--cve")
    p.add_argument("--cwe")
    p.add_argument("--cvss")
    p.add_argument("--negative-controls")
    p.add_argument("--root-cause")
    p.add_argument("--variant-analysis")
    p.add_argument("--patch-diff")
    p.add_argument("--exploitability")
    p.add_argument("--disclosure-quality")
    p.add_argument("--safety-notes")
    p.add_argument("--proof", choices=["not_started", "passed", "failed"])
    p.set_defaults(func=_h.cmd_candidate_set)

    p = sub.add_parser("candidates", help="list candidates")
    p.add_argument("run_dir")
    p.set_defaults(func=_h.cmd_candidates)

    p = sub.add_parser("prove", help="run a bounded local proof command")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--cmd", required=True)
    p.add_argument("--shell", action="store_true", help="run through the shell; default is argv parsing with shlex")
    p.add_argument("--cwd", help="proof working directory; default is an isolated evidence directory")
    p.add_argument("--timeout", type=int, default=120)
    p.add_argument("--cpu-seconds", type=int, default=0)
    p.add_argument("--memory-mb", type=int, default=0)
    p.add_argument("--file-mb", type=int, default=50)
    p.add_argument("--max-output-chars", type=int, default=200000)
    p.set_defaults(func=_h.cmd_prove)

    p = sub.add_parser("variant", help="search for sibling surfaces by candidate root cause and sink terms")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--pattern", action="append", help="extra fixed-string search pattern")
    p.add_argument("--path", action="append", help="limit search to a relative source path")
    p.add_argument("--max-hits", type=int, default=25)
    p.add_argument("--timeout", type=int, default=45)
    p.add_argument("--notes")
    p.set_defaults(func=_h.cmd_variant)

    p = sub.add_parser("patch-diff", help="capture git patch/advisory review artifacts for a candidate")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--base", required=True, help="base git ref")
    p.add_argument("--head", required=True, help="head git ref")
    p.add_argument("--path", action="append", help="limit diff to a relative source path")
    p.add_argument("--grep", action="append", help="git diff -G pattern to summarize")
    p.add_argument("--context", type=int, default=3)
    p.add_argument("--timeout", type=int, default=60)
    p.add_argument("--max-patch-chars", type=int, default=120000)
    p.add_argument("--notes")
    p.set_defaults(func=_h.cmd_patch_diff)

    p = sub.add_parser("source-graph", help="extract a lightweight source graph for high-value surfaces")
    p.add_argument("run_dir")
    p.add_argument("--glob", action="append", help="rg glob filter, e.g. *.go")
    p.add_argument("--include-tests", action="store_true", help="include tests, tools, mocks, and testdata")
    p.add_argument("--max-hits", type=int, default=200)
    p.add_argument("--sample-hits", type=int, default=20)
    p.add_argument("--timeout", type=int, default=60)
    p.set_defaults(func=_h.cmd_source_graph)

    p = sub.add_parser("cluster-variants", help="cluster latest variant-analysis hits by file and rough symbol")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--max-clusters", type=int, default=30)
    p.add_argument("--max-hits", type=int, default=20)
    p.set_defaults(func=_h.cmd_cluster_variants)

    p = sub.add_parser("score", help="score candidate quality from proof, novelty, and evidence fields")
    p.add_argument("run_dir")
    p.add_argument("candidate_id", nargs="?")
    p.add_argument("--fail-under", type=int, default=0)
    p.set_defaults(func=_h.cmd_score)

    p = sub.add_parser("hypothesize", help="generate research hypotheses from the source graph")
    p.add_argument("run_dir")
    p.add_argument("--max-hypotheses", type=int, default=12)
    p.add_argument("--files-per-hypothesis", type=int, default=8)
    p.set_defaults(func=_h.cmd_hypothesize)

    p = sub.add_parser("patch-mine", help="mine git diff ranges for security-relevant changes")
    p.add_argument("run_dir")
    p.add_argument("--range", action="append", help="git diff range, e.g. v1.0.0..v1.1.0")
    p.add_argument("--path", action="append", help="limit mining to a relative source path")
    p.add_argument("--grep", action="append", help="security pattern for git diff -G")
    p.add_argument("--max-matches", type=int, default=40)
    p.add_argument("--timeout", type=int, default=60)
    p.set_defaults(func=_h.cmd_patch_mine)

    p = sub.add_parser("proof-plan", help="generate a proof and negative-control plan for a candidate")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--level")
    p.add_argument("--positive")
    p.add_argument("--cleanup")
    p.set_defaults(func=_h.cmd_proof_plan)

    p = sub.add_parser("semantic-graph", help="extract function-level categories and lightweight call edges")
    p.add_argument("run_dir")
    p.add_argument("--path", action="append", help="limit extraction to a source file or directory")
    p.add_argument("--include-tests", action="store_true", help="include tests, tools, mocks, and testdata")
    p.add_argument("--max-files", type=int, default=2000)
    p.add_argument("--max-functions", type=int, default=5000)
    p.add_argument("--max-edges", type=int, default=10000)
    p.add_argument("--max-targets-per-call", type=int, default=3)
    p.add_argument("--sample-functions", type=int, default=80)
    p.set_defaults(func=_h.cmd_semantic_graph)

    p = sub.add_parser("flow-trace", help="map candidate terms to functions using the semantic graph")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--term", action="append", help="extra term to trace")
    p.add_argument("--only-terms", action="store_true", help="trace only explicit --term values")
    p.add_argument("--path", action="append", help="limit rg term search to a relative source path")
    p.add_argument("--include-tests", action="store_true", help="include tests, tools, mocks, and testdata")
    p.add_argument("--max-hits", type=int, default=80)
    p.add_argument("--max-functions", type=int, default=40)
    p.add_argument("--max-hits-per-function", type=int, default=10)
    p.add_argument("--timeout", type=int, default=60)
    p.set_defaults(func=_h.cmd_flow_trace)

    p = sub.add_parser("test-skeleton", help="generate a proof-test skeleton for a candidate")
    p.add_argument("run_dir")
    p.add_argument("candidate_id")
    p.add_argument("--framework", default="go")
    p.add_argument("--test-name")
    p.set_defaults(func=_h.cmd_test_skeleton)

    p = sub.add_parser("ledger-sqlite", help="sync candidate ledger to or from SQLite")
    p.add_argument("run_dir")
    p.add_argument("--db", help="SQLite DB path; default is <run_dir>/candidates.sqlite")
    p.add_argument("--from-sqlite", action="store_true", help="replace candidates.yaml from SQLite candidate_json rows")
    p.set_defaults(func=_h.cmd_ledger_sqlite)

    p = sub.add_parser("ingest-blackbox-run", help="ingest guarded blackbox evidence into harness artifacts")
    p.add_argument("run_dir")
    p.add_argument("evidence_dir")
    p.add_argument("--create-candidates", action="store_true")
    p.add_argument("--include-info", action="store_true")
    p.add_argument("--max-findings", type=int, default=100)
    p.add_argument("--max-file-mb", type=int, default=10)
    p.set_defaults(func=_h.cmd_ingest_blackbox_run)

    p = sub.add_parser("taint-trace", help="run lightweight intra-procedural taint tracing from source terms to sink categories")
    p.add_argument("run_dir")
    p.add_argument("--source-regex", help="override source regex")
    p.add_argument("--sink-category", action="append", help="GRAPH_QUERIES category to treat as sink")
    p.add_argument("--max-traces", type=int, default=100)
    p.add_argument(
        "--unguarded-only",
        action="store_true",
        help="drop flows constrained by a recognized guard (whitelist/validation/signature/parameterized bind/constrained dispatch)",
    )
    p.set_defaults(func=_h.cmd_taint_trace)

    p = sub.add_parser("guard-drift", help="find sink functions that lack guards used by sibling sink paths")
    p.add_argument("run_dir")
    p.add_argument("--guard-regex", help="override the security guard regex")
    p.add_argument("--sink-category", action="append", help="GRAPH_QUERIES category to compare")
    p.add_argument("--path", action="append", help="limit extraction to a source file or directory")
    p.add_argument("--include-tests", action="store_true", help="include tests, tools, mocks, and testdata")
    p.add_argument("--max-files", type=int, default=2000)
    p.add_argument("--max-functions", type=int, default=7000)
    p.add_argument("--max-candidates", type=int, default=80)
    p.add_argument("--examples", type=int, default=3, help="guarded sibling examples per candidate")
    p.add_argument("--require-guarded-sibling", action="store_true", help="suppress broad sink inventory without a guarded sibling")
    p.add_argument("--create-candidates", action="store_true")
    p.add_argument("--create-limit", type=int, default=5)
    p.set_defaults(func=_h.cmd_guard_drift)

    p = sub.add_parser("report", help="generate a triage draft from the ledger")
    p.add_argument("run_dir")
    p.set_defaults(func=_h.cmd_report)

    p = sub.add_parser("reference-add", help="append a trusted reference to the run ledger")
    p.add_argument("run_dir")
    p.add_argument("--kind", required=True, choices=["advisory", "cve", "commit", "blog", "paper", "program", "source", "other"])
    p.add_argument("--title", required=True)
    p.add_argument("--url")
    p.add_argument("--path")
    p.add_argument("--candidate-id")
    p.add_argument("--notes")
    p.add_argument("--trusted", action="store_true")
    p.set_defaults(func=_h.cmd_reference_add)

    p = sub.add_parser("dashboard", help="generate an HTML run dashboard")
    p.add_argument("run_dir")
    p.set_defaults(func=_h.cmd_dashboard)

    p = sub.add_parser("status", help="summarize run state")
    p.add_argument("run_dir")
    p.add_argument("--json", action="store_true")
    p.set_defaults(func=_h.cmd_status)
    return parser


def main(argv: list[str] | None = None) -> int:
    parser = build_parser()
    args = parser.parse_args(argv)
    args.func(args)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
