"""Tests for the tarball-vs-git supply-chain diff probe.

Per the xz-utils case study
(`knowledge/case_studies/xz_utils_supply_chain.md`): release tarballs
can contain files NOT present in the corresponding git tag (build
script tweaks, vendored binary blobs, malicious m4 macros, etc.). The
probe compares two directory trees (an extracted release tarball and
a git checkout of the same version) and emits:

  - ``tarball_only``    files present in the tarball but absent from
                        the git tree (the xz-utils signal)
  - ``content_differs`` files present in both but with different
                        SHA-256 hashes (the upstream patch was not in
                        git but lives in the published tarball)
  - ``git_only``        files in git but missing from the tarball
                        (lower-EV; build-time exclusions are common)

A built-in allowlist suppresses known-benign autogenerated paths
(``configure``, ``Makefile.in``, ``aclocal.m4``, etc.) so the
xz-utils signal stays clear.
"""
from __future__ import annotations

import hashlib
import tarfile
import textwrap
from pathlib import Path

import pytest


@pytest.fixture
def differ():
    from source.supply_chain_diff import SupplyChainDiffer
    return SupplyChainDiffer()


def _write_tree(root: Path, files: dict[str, str]) -> Path:
    root.mkdir(parents=True, exist_ok=True)
    for relpath, content in files.items():
        full = root / relpath
        full.parent.mkdir(parents=True, exist_ok=True)
        full.write_text(content, encoding="utf-8")
    return root


def test_identical_trees_have_no_findings(differ, tmp_path):
    files = {"a.js": "hi", "lib/b.js": "world", "package.json": "{}"}
    a = _write_tree(tmp_path / "tarball", files)
    b = _write_tree(tmp_path / "git", files)
    assert differ.diff(tarball_root=a, git_root=b) == []


def test_tarball_only_file_is_flagged(differ, tmp_path):
    a = _write_tree(tmp_path / "tarball", {
        "a.js": "hi",
        "build/extra.js": "DROP_TABLE",  # only in tarball
    })
    b = _write_tree(tmp_path / "git", {"a.js": "hi"})
    findings = differ.diff(tarball_root=a, git_root=b)
    kinds = [(f["kind"], f["path"]) for f in findings]
    assert ("tarball_only", "build/extra.js") in kinds


def test_content_differs_is_flagged(differ, tmp_path):
    a = _write_tree(tmp_path / "tarball", {"a.js": "hi PATCHED"})
    b = _write_tree(tmp_path / "git", {"a.js": "hi"})
    findings = differ.diff(tarball_root=a, git_root=b)
    assert len(findings) == 1
    f = findings[0]
    assert f["kind"] == "content_differs"
    assert f["path"] == "a.js"
    assert f["tarball_sha256"] != f["git_sha256"]


def test_git_only_files_are_flagged_with_lower_severity(differ, tmp_path):
    a = _write_tree(tmp_path / "tarball", {"a.js": "hi"})
    b = _write_tree(tmp_path / "git", {"a.js": "hi", ".github/workflows/ci.yml": "ci"})
    findings = differ.diff(tarball_root=a, git_root=b)
    kinds = [(f["kind"], f["path"], f["severity"]) for f in findings]
    assert ("git_only", ".github/workflows/ci.yml", "low") in kinds


def test_autogenerated_paths_are_suppressed(differ, tmp_path):
    # build artefacts that legitimately live only in the tarball
    a = _write_tree(tmp_path / "tarball", {
        "configure": "#!/bin/sh",
        "Makefile.in": "x",
        "aclocal.m4": "x",
        "build/extra.js": "DROP_TABLE",  # genuine suspect
    })
    b = _write_tree(tmp_path / "git", {})
    findings = differ.diff(tarball_root=a, git_root=b)
    paths = [f["path"] for f in findings]
    assert "configure" not in paths
    assert "Makefile.in" not in paths
    assert "aclocal.m4" not in paths
    assert "build/extra.js" in paths


def test_severity_high_for_tarball_only_code_files(differ, tmp_path):
    a = _write_tree(tmp_path / "tarball", {
        "src/sneaky.js": "evil",
        "docs/readme.md": "harmless",
    })
    b = _write_tree(tmp_path / "git", {})
    findings = {f["path"]: f for f in differ.diff(tarball_root=a, git_root=b)}
    # Code files are high; docs/markdown are medium.
    assert findings["src/sneaky.js"]["severity"] == "high"
    assert findings["docs/readme.md"]["severity"] == "medium"


def test_diff_from_tarball_archive(differ, tmp_path):
    # Build a .tar.gz on the fly and pass the path directly -- the
    # probe should extract it internally.
    src = tmp_path / "src"
    _write_tree(src, {"a.js": "hi", "build/extra.js": "DROP_TABLE"})
    archive = tmp_path / "pkg.tar.gz"
    with tarfile.open(archive, "w:gz") as tar:
        for p in src.rglob("*"):
            if p.is_file():
                tar.add(p, arcname=str(p.relative_to(src)))
    git = _write_tree(tmp_path / "git", {"a.js": "hi"})
    findings = differ.diff(tarball_root=archive, git_root=git)
    paths = [f["path"] for f in findings]
    assert "build/extra.js" in paths


def test_walk_skips_dot_git_and_node_modules(differ, tmp_path):
    # A normal git checkout has `.git/` (noise) and may have
    # `node_modules/` (vendored deps not part of the publication).
    # Neither should produce findings.
    a = _write_tree(tmp_path / "tarball", {"a.js": "hi"})
    b = _write_tree(tmp_path / "git", {
        "a.js": "hi",
        ".git/HEAD": "ref: refs/heads/main",
        ".git/objects/pack/pack-abc.idx": "binary-ish",
        "node_modules/leftpad/index.js": "vendored",
    })
    findings = differ.diff(tarball_root=a, git_root=b)
    paths = [f["path"] for f in findings]
    assert not any(p.startswith(".git/") for p in paths)
    assert not any(p.startswith("node_modules/") for p in paths)


def test_probe_run(tmp_path):
    from probes.base import ProbeContext
    from probes.supply_chain_diff import SupplyChainDiffProbe

    tarball = _write_tree(tmp_path / "tarball", {"a.js": "hi", "extra.js": "evil"})
    git = _write_tree(tmp_path / "git", {"a.js": "hi"})
    ctx = ProbeContext(
        run_dir=tmp_path,
        target={},
        candidate={"id": "CAND-SC"},
        knobs={"tarball_root": str(tarball), "git_root": str(git)},
    )
    result = SupplyChainDiffProbe().run(ctx)
    assert result["name"] == "supply_chain_diff"
    assert result["finding_count"] == 1
    assert result["findings"][0]["path"] == "extra.js"
    assert result["findings"][0]["kind"] == "tarball_only"


def test_probe_missing_knobs_errors(tmp_path):
    from probes.base import ProbeContext
    from probes.supply_chain_diff import SupplyChainDiffProbe

    ctx = ProbeContext(run_dir=tmp_path, target={}, candidate={}, knobs={})
    result = SupplyChainDiffProbe().run(ctx)
    assert "error" in result
    assert result["finding_count"] == 0
